version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - mkdocs
        - mkdocstrings[python]
        - mkdocs-material
