version: 2

mkdocs:
  configuration: mkdocs.yml

python:
  version: 3.11
  install:
    - method: pip
      path: .
      extra_requirements:
        - mkdocs
        - mkdocstrings[python]
        - mkdocs-material
